id: P009529
initial_creation_type: ocr
source_metadata:
  id: bdr:W1KG9086
  title: ཐལ་བཟློག་གི་དཀའ་བའི་གནས་གཏན་ལ་འབེབས་པ་འཇམ་པའི་དབྱངས་སྒོམ་སྡེ་ནམ་མཁའ་རྒྱལ་མཚན་གྱིས་མཛད་པ།
  author: ''
  volumes:
    358c44494285487697355b1eea6430e9:
      image_group_id: I1KG9107
      title: ''
      volume_number: 1
      total_pages: 82
      base_file: v001.txt
