id: P009529
initial_creation_type: ocr
source_metadata:
  id: bdr:W1KG9086
  title: ཐལ་བཟློག་གི་དཀའ་བའི་གནས་གཏན་ལ་འབེབས་པ་འཇམ་པའི་དབྱངས་སྒོམ་སྡེ་ནམ་མཁའ་རྒྱལ་མཚན་གྱིས་མཛད་པ།
  author: ''
  volumes: {}
