id: IAA2B66E5
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-28T17:28:47+00:00'
last_modified: '2022-06-08T11:40:37.817400+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1KG9086
  title: ཐལ་བཟློག་གི་དཀའ་བའི་གནས་གཏན་ལ་འབེབས་པ་འཇམ་པའི་དབྱངས་སྒོམ་སྡེ་ནམ་མཁའ་རྒྱལ་མཚན་གྱིས་མཛད་པ།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    B43E:
      image_group_id: I1KG9107
      title: ''
      total_pages: 82
      order: 1
      base_file: B43E.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
