id: IAA2B66E5
legacy_id: P009529
ocr_import_info:
  bdrc_scan_id: W1KG9086
  source: bdrc
  ocr_info:
    timestamp: '2020-03-28T17:28:12'
    imagesfolder: images
  batch_id: batch001
  software_id: vision
  expected_default_language: bo
  op_import_options: {}
  op_import_version: 1.0.0
default_language: bo
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-08-31T18:17:44.002914+00:00'
last_modified: 2022-09-01 02:17:49.365298
parser: https://github.com/OpenPecha/Toolkit/blob/7f57883d84bc10351527a49ee6ce970ace404e50/openpecha/formatters/google_ocr.py
source_metadata:
  id: http://purl.bdrc.io/resource/W1KG9086
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  reproduction_of: http://purl.bdrc.io/resource/MW1KG9086
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: ཐལ་བཟློག་གི་དཀའ་བའི་གནས་གཏན་ལ་འབེབས་པ་འཇམ་པའི་དབྱངས་སྒོམ་སྡེ་ནམ་མཁའ་རྒྱལ་མཚན་གྱིས་མཛད་པ།
  author: སྒོམ་སྡེ་བ་ནམ་མཁའ་རྒྱལ་མཚན།
statistics:
  ocr_word_mean_confidence_index: 0.74261100401032
  ocr_word_median_confidence_index: 0.8199999928474426
quality: null
bases:
  I1KG9107:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1KG9107
      total_pages: 82
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I1KG9107.txt
    statistics:
      ocr_word_median_confidence_index: 0.8199999928474426
      ocr_word_mean_confidence_index: 0.74261100401032
    legacy_id: v001
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
